### ISSUE TITLE
[Bug] Advertising "Free" games on Epic that are not Free

### ISSUE THREAD

**Issue by pironic** [moonstar-x/discord-free-games-notifier#21]
We should add one more check to this line: 

https://github.com/moonstar-x/discord-free-games-notifier/blob/ef4c0c18c5b0611ac4791d2b39bfa11e9e9550a3/src/classes/providers/EpicGamesProvider.js#L33

`&& game.price.totalPrice.discountPrice === 0`

**Comment by pironic** [comment]
As per #14, would you suggest both date and discountPrice = 0?

**Comment by moonstar-x** [comment]
It would seem that just the discountPrice is enough, I have yet to find a game offer that would have a discountPrice of 0 and still be a false positive.

**Comment by pironic** [comment]
Alright, i'll make a pull request for you to make it easier to apply :)
