### ISSUE TITLE
Update to Djs.13/Djs.14

### ISSUE THREAD

**Issue by moonstar-x** [moonstar-x/discord-free-games-notifier#23]
#### :zap: Describe the New Feature

The bot has no Slash commands currently, and since the deadline for implementing this has ended for verified bots, the official bot is currently unusable.

I'm afraid I can only start working on this until January 2023 because of college and work.

Fear not, this project is not abandoned but it is on hold until then.

**Comment by fred8044** [comment]
Hello, I hope it is not abandoned, I would have liked to install it :)

**Comment by moonstar-x** [comment]
This is done in #26.
